<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <MauiVersion>10.0.100</MauiVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Evergine.Common" Version="2026.5.26.1667" />
    <PackageVersion Include="Evergine.Components" Version="2026.5.26.1667" />
    <PackageVersion Include="Evergine.Framework" Version="2026.5.26.1667" />
    <PackageVersion Include="Evergine.iOS" Version="2026.5.26.1667" />
    <PackageVersion Include="Evergine.Mathematics" Version="2026.5.26.1667" />
    <PackageVersion Include="Evergine.Metal" Version="2026.5.26.1667" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Debug" Version="10.0.8" />
    <PackageVersion Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
    <PackageVersion Include="SkiaSharp" Version="4.151.2" />
    <PackageVersion Include="SkiaSharp.NativeAssets.iOS" Version="4.151.2" />
  </ItemGroup>
</Project>
